### ISSUE TITLE
Support matches short hands

### ISSUE THREAD

**Issue by megawac** [brianneisler/mudash#3]
For example

```js

_.filter(list, {
   a: 1
})
```

See https://lodash.com/docs/4.17.2#iteratee

**Comment by brianneisler** [comment]
Good idea. Should be easy enough to implement. Will take a crack at it today.

**Comment by brianneisler** [comment]
@megawac well that took a bit more work than I anticipated. Should be working now though. Still putting together unit tests so feel free to open any issues you run in to. Thanks!

**Comment by megawac** [comment]
Awesome thank you!
