### ISSUE TITLE
chunk

### ISSUE THREAD

**Issue by megawac** [brianneisler/mudash#5]
Chunk would be a nice to have feature (with a simple implementation)

http://stackoverflow.com/a/38765329/1517919

**Comment by brianneisler** [comment]
Hey @megawac,

Thanks for the request!

I believe the chunk method has already been implemented in mudash. 

The available methods haven't been documented yet but the next release will have a first pass at the API docs to help with this.

Let me know if you have any issues with the existing chunk method. The signature should be the same as lodash's.

**Comment by megawac** [comment]
Ah missed it, I was looking in the core folder. My bad!
