### ISSUE TITLE
omitBy should returns an object

### ISSUE THREAD

**Issue by calvintychan** [brianneisler/mudash#9]
According to the lodash doc, the method _.omitBy should return an object.
The current method is returning an array. This is likely because the filterNot method is using the _.reject method.

**Comment by brianneisler** [comment]
@calvintychan thanks for the bug report! Can you add some example code showing the issue?

**Comment by calvintychan** [comment]
```
const mudash = require('mudash');
const lodash = require('lodash');

var object = { 'a': 1, 'b': 2, 'c': 3 };

lodash.omitBy(object, n => n % 2); // => { 'b': '2' }
mudash.omitBy(object, n => n % 2); // => [ 2 ]
```

**Comment by brianneisler** [comment]
Thanks @calvintychan! Will have a look at this soon.
